name: CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install deps
        run: npm ci
      - name: Test unit
        run: npm run test-ci
      - name: Test e2e
        run: npx playwright install --with-deps && npm run e2e-ci
